name:                ect
version:             0.1.0.0
github:              "gaps-closure/ect"
license:             BSD3
author:              "GAPS CLOSURE project"
maintainer:          "sedwards@cs.columbia.edu"
copyright:           "2020 GAPS CLOSURE project"

extra-source-files:
- README.md
- LICENSE

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gaps-closure/ect#readme>

dependencies:
- base >= 4.7 && < 5
    
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -ddump-splices  # For debugging Template Haskell:
  - -ddump-to-file  # more $(find . -name "*splices")
  dependencies:
  - template-haskell
  - llvm-hs-pure >= 9.0.0
  - llvm-hs >= 9.0.1
  - z3 >= 408.2
  - transformers
  - containers
  - bytestring
  - utf8-string

executables:
  ect:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -dynamic          # Needed for linking with the Z3 library
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
    
    dependencies:
    - z3 >= 408.2
    - llvm-hs-pure >= 9.0.0
    - llvm-hs >= 9.0.1
    - transformers
    - bytestring
    - utf8-string
    - containers
    - ect

  printTypes:
    main:                PrintTypes.hs
    ghc-options:
    - -main-is PrintTypes
    - -dynamic
    - -Wall
    source-dirs:         app
    
    dependencies:
    - z3 >= 408.2
    - llvm-hs-pure >= 9.0.0
    - llvm-hs >= 9.0.1
    - bytestring
    - utf8-string
    - containers
    - transformers
    - ect

# stack build -v --ghc-options="-v" --cabal-verbose > log 2>&1
# shows the sausage being made

# Adding Template-haskell produces the following compilation error:
#
# [1 of 2] Compiling Main
# <command line>: libz3.so: cannot open shared object file: No such file or directory
#
#--  While building package ect-0.1.0.0 (scroll up to its section to see the error) using:
#      /home/sedwards/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.2 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0 build lib:ect exe:ect --ghc-options " -fdiagnostics-color=always"

# This cures the problem, but not elegantly
#
# LD_LIBRARY_PATH=z3-4.8.8-x64-ubuntu-16.04/bin stack build

# https://ro-che.info/articles/2017-07-26-haskell-library-in-c-project