resolver: lts-15.3

packages:
- .

extra-deps:
- git: git@github.com:gaps-closure/haskell-z3.git
  commit: fad1fe11ab9dda192bb89e90ea14a80d90140fcb

extra-include-dirs:
  - z3-4.8.8/include

extra-lib-dirs:
  - z3-4.8.8/lib
