resolver: lts-15.3

packages:
- .

extra-deps:
- git: https://github.com/gaps-closure/haskell-z3.git
  commit: fad1fe11ab9dda192bb89e90ea14a80d90140fcb
- git: https://github.com/llvm-hs/llvm-hs.git
  commit: b518fe11241e8aea40760eee9cd95421ef772646
  subdirs:
  - llvm-hs
  - llvm-hs-pure
# - llvm-hs-pretty-0.9.0.0@sha256:b7a5de5f3dd97893d19d2b47af1e4dd8d075a5cf57062180a912d1f3ef1def60

extra-include-dirs:
  - z3-4.8.8/include

extra-lib-dirs:
  - z3-4.8.8/lib
